name: GitHub Actions Demo

on:
  push:
    branches:
      - '101399169-Talalovic'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Java JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'adoptopenjdk'  # Update this line to 'adoptium'

    - name: Build with Maven
      run: mvn clean install

    - name: Run Tests
      run: mvn test
