name: GitHub Actions Demo

on:
  push:
    branches:
      - '101399169-Talalovic'  # Trigger only when pushing to this branch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Set up Java JDK 11 using Adoptium (Temurin)
      - name: Set up Java JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'  # This is the missing part that needs to be specified

      # Step 3: Cache Maven dependencies
      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # Step 4: Build with Maven
      - name: Build with Maven
        run: mvn clean install -B  # '-B' for batch mode, suppresses interactive prompts

      # Step 5: Run Tests
      - name: Run Tests
        run: mvn test  # Run the tests if you have any in the project
