name: Java Maven Build

on:
  push:
    branches: ["101399169-Talalovic"]  # Trigger on the specific branch
  pull_request:
    branches: ["101399169-Talalovic"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout repository
      - uses: actions/checkout@v4
      
      # Step 2: Set up Java JDK 11 using Adoptium (Temurin)
      - name: Set up Java JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'  # Using 'temurin' from Adoptium distribution

      # Step 3: Cache Maven dependencies
      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # Step 4: Build with Maven
      - name: Build with Maven
        run: mvn clean install -B  # '-B' for batch mode to suppress interactive prompts

      # Step 5: Run Tests
      - name: Run Tests
        run: mvn test
